arch: DepthAttentionUNet
batch_size: 8
dataset: resized_tree_dataset_512
deep_supervision: false
depth_ext: .png
early_stopping: 25
epochs: 200
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
input_channels: 3
input_h: 512
input_w: 512
loss: BCEDiceLoss
lr: 0.001
mask_ext: .png
milestones: 50,150
min_lr: 1.0e-05
momentum: 0.9
name: resized_tree_dataset_512_DepthAttentionUNet_woDS2023-03-14_08:12:27.437440
nesterov: true
num_classes: 1
num_workers: 4
optimizer: SGD
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
